// src/app/privacy/page.tsx
import type { Metadata } from "next";
import { PageHero } from "@/components/sections/page-hero";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "West Papua Care privacy policy - how we collect, use, and protect your personal information.",
};

export default function PrivacyPage() {
  return (
    <>
      <PageHero
        label="LEGAL"
        title="Privacy Policy"
        subtitle="How we collect, use, and protect your personal information"
      />

      <section className="py-16 lg:py-24 bg-[var(--color-off-white)]">
        <div className="max-w-[var(--max-width-content)] mx-auto px-8">
          <div className="max-w-[800px] mx-auto prose prose-lg">
            <p className="text-sm text-[var(--color-gray)] mb-8">
              Last updated: December 2024
            </p>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              Introduction
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
              West Papua Care (&quot;we,&quot; &quot;our,&quot; or
              &quot;us&quot;) is committed to protecting your privacy. This
              Privacy Policy explains how we collect, use, and safeguard your
              personal information when you visit our website or interact with
              our organization.
            </p>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              Information We Collect
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-4">
              We may collect the following types of information:
            </p>
            <ul className="list-disc pl-8 mb-6 text-[var(--color-gray)]">
              <li className="mb-2">
                <strong>Contact Information:</strong> Name, email address, and
                other details you provide when contacting us or subscribing to
                our newsletter.
              </li>
              <li className="mb-2">
                <strong>Donation Information:</strong> Payment details and
                billing information when you make a donation (processed securely
                by third-party payment processors).
              </li>
              <li className="mb-2">
                <strong>Usage Data:</strong> Information about how you use our
                website, including pages visited and time spent on the site.
              </li>
            </ul>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              How We Use Your Information
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-4">
              We use the information we collect to:
            </p>
            <ul className="list-disc pl-8 mb-6 text-[var(--color-gray)]">
              <li className="mb-2">Process donations and send receipts</li>
              <li className="mb-2">
                Send newsletters and updates about our work (with your consent)
              </li>
              <li className="mb-2">
                Respond to your inquiries and provide support
              </li>
              <li className="mb-2">
                Improve our website and communications
              </li>
              <li className="mb-2">
                Comply with legal obligations and protect our rights
              </li>
            </ul>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              Information Sharing
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
              We do not sell, trade, or rent your personal information to third
              parties. We may share your information with trusted service
              providers who assist us in operating our website and conducting
              our activities, subject to confidentiality obligations.
            </p>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              Data Security
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
              We implement appropriate technical and organizational measures to
              protect your personal information against unauthorized access,
              alteration, disclosure, or destruction. However, no method of
              transmission over the Internet is 100% secure.
            </p>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              Your Rights
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-4">
              Depending on your location, you may have the right to:
            </p>
            <ul className="list-disc pl-8 mb-6 text-[var(--color-gray)]">
              <li className="mb-2">
                Access the personal information we hold about you
              </li>
              <li className="mb-2">
                Request correction of inaccurate information
              </li>
              <li className="mb-2">
                Request deletion of your personal information
              </li>
              <li className="mb-2">
                Opt out of marketing communications at any time
              </li>
            </ul>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              Cookies
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
              Our website may use cookies to enhance your experience. Cookies
              are small files stored on your device that help us understand how
              you use our site. You can control cookie settings through your
              browser preferences.
            </p>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              Third-Party Links
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
              Our website may contain links to external sites. We are not
              responsible for the privacy practices of these third-party
              websites. We encourage you to review their privacy policies.
            </p>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              Changes to This Policy
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
              We may update this Privacy Policy from time to time. We will
              notify you of any significant changes by posting the new policy on
              this page with an updated revision date.
            </p>

            <h2 className="text-2xl font-semibold text-[var(--color-charcoal)] mt-8 mb-4">
              Contact Us
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
              If you have questions about this Privacy Policy or our data
              practices, please contact us at{" "}
              <a
                href="mailto:info@westpapuacare.org"
                className="text-[var(--color-burnt-orange)] hover:underline"
              >
                info@westpapuacare.org
              </a>
              .
            </p>
          </div>
        </div>
      </section>
    </>
  );
}

// src/routes/privacy/+page.svelte
<section class="page-hero">
	<div class="page-hero__container">
		<div class="section-label">[ LEGAL ]</div>
		<h1 class="page-hero__title">Privacy Policy</h1>
		<p class="page-hero__subtitle">
			How we collect, use, and protect your personal information
		</p>
	</div>
</section>

<section class="content-section">
	<div class="content-container">
		<div class="policy-content">
			<p class="effective-date">
				<strong>Effective Date:</strong> November 21, 2025<br />
				<strong>Last Updated:</strong> November 21, 2025
			</p>

			<div class="intro-text">
				<p>
					West Papua Care ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your personal information when you interact with our website, subscribe to our newsletter, or engage with our conservation programs.
				</p>
			</div>

			<h2>1. Organization Details</h2>
			<p>
				West Papua Care operates as an independent non-governmental organization focused on community-led marine conservation in Misool, Raja Ampat, Indonesia. We function as the data controller for all personal information we collect.
			</p>
			<p>
				<strong>Contact Information:</strong><br />
				Email: <a href="mailto:westpapuacare@gmail.com">westpapuacare@gmail.com</a><br />
				WhatsApp: <a href="https://wa.me/6282266608012">+62 822 6660 8012</a><br />
				Location: Misool, Raja Ampat, West Papua, Indonesia
			</p>
			<p>
				For privacy-specific inquiries, please contact us at <a href="mailto:westpapuacare@gmail.com">westpapuacare@gmail.com</a> with "Privacy" in the subject line.
			</p>

			<h2>2. Legal Basis for Processing</h2>
			<p>We process your personal data based on:</p>
			<ul>
				<li><strong>Consent:</strong> When you subscribe to our newsletter, make a donation, or voluntarily provide information</li>
				<li><strong>Legitimate Interests:</strong> To improve our services, communicate about our conservation work, and fulfill our mission</li>
				<li><strong>Legal Compliance:</strong> To meet regulatory requirements and protect against fraud</li>
				<li><strong>Contract Performance:</strong> When necessary to fulfill partnership agreements or service delivery</li>
			</ul>

			<h2>3. Information We Collect</h2>

			<h3>Information You Provide</h3>
			<p>When you interact with us, you may voluntarily provide:</p>
			<ul>
				<li>Name and email address (for newsletters and communications)</li>
				<li>Contact information (phone number, mailing address for donors and partners)</li>
				<li>Payment information (processed securely through third-party payment processors)</li>
				<li>Communication preferences and feedback</li>
				<li>Professional information (for researchers and partnership inquiries)</li>
			</ul>

			<h3>Information Collected Automatically</h3>
			<p>When you visit our website, we may automatically collect:</p>
			<ul>
				<li>IP address and device information</li>
				<li>Browser type and operating system</li>
				<li>Pages viewed and time spent on our website</li>
				<li>Referring website or source</li>
				<li>Email engagement data (open rates, click-through rates for newsletters)</li>
			</ul>

			<h2>4. How We Use Your Information</h2>
			<p>We use your personal information to:</p>
			<ul>
				<li>Deliver newsletters and updates about our conservation work</li>
				<li>Process donations and acknowledge contributions</li>
				<li>Respond to inquiries and provide customer support</li>
				<li>Improve our website and user experience</li>
				<li>Analyze engagement and measure impact</li>
				<li>Communicate about partnership opportunities</li>
				<li>Comply with legal and regulatory requirements</li>
				<li>Protect against fraud and ensure security</li>
			</ul>
			<p class="highlight">
				<strong>We never sell your personal information.</strong> Your data is used exclusively to support our conservation mission and maintain relationships with our supporters.
			</p>

			<h2>5. Information Sharing</h2>
			<p>We may share your information with trusted third-party service providers who help us operate:</p>
			<ul>
				<li><strong>Email Service Providers:</strong> For newsletter delivery and communications</li>
				<li><strong>Payment Processors:</strong> For secure donation processing</li>
				<li><strong>Website Hosting:</strong> For site operation and maintenance</li>
				<li><strong>Analytics Services:</strong> To understand website usage and improve services</li>
				<li><strong>Cloud Storage:</strong> For secure data backup and storage</li>
			</ul>
			<p>
				All service providers are carefully selected and required to maintain confidentiality and security of your data. We only share the minimum information necessary for them to provide their services.
			</p>
			<p>
				We may also disclose information when required by law, to protect our rights, or to protect the safety of others.
			</p>

			<h2>6. Data Retention</h2>
			<p>We retain your personal information for different periods depending on the purpose:</p>
			<ul>
				<li><strong>Active Subscribers:</strong> Data is retained while you remain subscribed to our communications</li>
				<li><strong>Unsubscribed Users:</strong> Information may be retained for up to 3 years for record-keeping and compliance purposes</li>
				<li><strong>Donor Information:</strong> Retained for 7 years to comply with financial record-keeping requirements</li>
				<li><strong>Analytics Data:</strong> Typically retained for approximately 2 years</li>
				<li><strong>Partnership Records:</strong> Retained for the duration of the partnership plus 3 years</li>
			</ul>
			<p>
				You may request early deletion of your data at any time by contacting us at <a href="mailto:westpapuacare@gmail.com">westpapuacare@gmail.com</a>.
			</p>

			<h2>7. Your Rights</h2>
			<p>You have the following rights regarding your personal information:</p>
			<ul>
				<li><strong>Access:</strong> Request a copy of the personal data we hold about you</li>
				<li><strong>Correction:</strong> Request correction of inaccurate or incomplete information</li>
				<li><strong>Deletion:</strong> Request deletion of your personal data</li>
				<li><strong>Restriction:</strong> Request restriction of processing in certain circumstances</li>
				<li><strong>Portability:</strong> Request transfer of your data to another service</li>
				<li><strong>Object:</strong> Object to processing based on legitimate interests</li>
				<li><strong>Withdraw Consent:</strong> Unsubscribe from communications at any time</li>
			</ul>
			<p>
				To exercise any of these rights, please contact us at <a href="mailto:westpapuacare@gmail.com">westpapuacare@gmail.com</a>. We will respond to your request within 30 days.
			</p>
			<p>
				To unsubscribe from our newsletter, click the "unsubscribe" link at the bottom of any email, or contact us directly.
			</p>

			<h2>8. Security Measures</h2>
			<p>We take the security of your personal information seriously and implement appropriate measures including:</p>
			<ul>
				<li>Encryption of data in transit and at rest</li>
				<li>Secure access controls and authentication</li>
				<li>Regular security assessments and updates</li>
				<li>Limited employee access to personal data</li>
				<li>Secure backup procedures</li>
			</ul>
			<p>
				While we strive to protect your information, no method of transmission over the internet is 100% secure. We cannot guarantee absolute security but continuously work to improve our protection measures.
			</p>

			<h2>9. International Data Transfers</h2>
			<p>
				West Papua Care operates in Indonesia. Your information may be transferred to and processed in countries outside of your residence, including the European Union and United States, where our service providers are located.
			</p>
			<p>
				When we transfer data internationally, we ensure appropriate safeguards are in place, such as standard contractual clauses or other legally approved mechanisms to protect your information.
			</p>

			<h2>10. Cookies and Tracking Technologies</h2>
			<p>
				Our website uses cookies and similar technologies to improve your experience and analyze site usage. Cookies are small text files stored on your device.
			</p>
			<p><strong>Types of cookies we use:</strong></p>
			<ul>
				<li><strong>Essential Cookies:</strong> Required for website functionality</li>
				<li><strong>Analytics Cookies:</strong> Help us understand how visitors use our site</li>
				<li><strong>Preference Cookies:</strong> Remember your settings and preferences</li>
			</ul>
			<p>
				You can control cookie settings through your browser preferences. Note that disabling certain cookies may affect website functionality.
			</p>

			<h2>11. Children's Privacy</h2>
			<p>
				Our website and services are not directed to individuals under the age of 16. We do not knowingly collect personal information from children. If we become aware that we have inadvertently collected information from a child under 16, we will take steps to delete it promptly.
			</p>
			<p>
				If you believe we have collected information from a child under 16, please contact us immediately at <a href="mailto:westpapuacare@gmail.com">westpapuacare@gmail.com</a>.
			</p>

			<h2>12. Third-Party Links</h2>
			<p>
				Our website may contain links to third-party websites, including social media platforms and partner organizations. We are not responsible for the privacy practices of these external sites. We encourage you to review their privacy policies before providing any personal information.
			</p>

			<h2>13. Changes to This Policy</h2>
			<p>
				We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. We will notify subscribers of material changes via email and update the "Last Updated" date at the top of this page.
			</p>
			<p>
				Continued use of our website and services after changes constitutes acceptance of the updated policy.
			</p>

			<h2>14. Contact Us</h2>
			<p>
				If you have questions, concerns, or requests regarding this Privacy Policy or how we handle your personal information, please contact us:
			</p>
			<div class="contact-box">
				<p>
					<strong>West Papua Care</strong><br />
					Email: <a href="mailto:westpapuacare@gmail.com">westpapuacare@gmail.com</a><br />
					WhatsApp: <a href="https://wa.me/6282266608012">+62 822 6660 8012</a><br />
					Location: Misool, Raja Ampat, West Papua, Indonesia
				</p>
				<p>
					For privacy-specific inquiries, please include "Privacy" in your email subject line.
				</p>
			</div>

			<p class="footer-note">
				This Privacy Policy is part of our commitment to transparency and protecting the privacy rights of our supporters, partners, and website visitors. Thank you for trusting West Papua Care with your information as we work together to protect the Coral Triangle's marine biodiversity.
			</p>
		</div>
	</div>
</section>

<style>
	.page-hero {
		background: var(--color-forest-green-deep);
		padding: clamp(8rem, 15vh, 12rem) 0 clamp(3rem, 6vh, 5rem);
		position: relative;
	}

	.page-hero::before {
		content: '';
		position: absolute;
		inset: 0;
		opacity: 0.03;
		background-image: radial-gradient(circle at 1px 1px, rgba(255, 255, 255, 0.15) 1px, transparent 1px);
		background-size: 40px 40px;
	}

	.page-hero__container {
		max-width: var(--max-width-content);
		margin: 0 auto;
		padding: 0 var(--spacing-xl);
		position: relative;
		z-index: 1;
		text-align: center;
	}

	.page-hero__title {
		font-size: clamp(2.5rem, 5vw, 4rem);
		font-weight: 700;
		line-height: 1.2;
		color: var(--color-off-white);
		margin-bottom: var(--spacing-lg);
	}

	.page-hero__subtitle {
		font-size: clamp(1.125rem, 2vw, 1.5rem);
		line-height: 1.6;
		color: rgba(255, 255, 255, 0.9);
		max-width: 800px;
		margin: 0 auto;
	}

	.content-section {
		padding: clamp(4rem, 8vh, 6rem) 0;
		background: var(--color-off-white);
	}

	.content-container {
		max-width: 900px;
		margin: 0 auto;
		padding: 0 var(--spacing-xl);
	}

	.policy-content {
		background: white;
		padding: var(--spacing-3xl);
		border-radius: 8px;
		box-shadow: var(--shadow-sm);
	}

	.effective-date {
		font-size: var(--font-size-sm);
		color: var(--color-gray);
		padding: var(--spacing-md);
		background: var(--color-cream);
		border-radius: 4px;
		margin-bottom: var(--spacing-2xl);
	}

	.intro-text {
		margin-bottom: var(--spacing-3xl);
	}

	.intro-text p {
		font-size: var(--font-size-lg);
		line-height: 1.7;
		color: var(--color-gray);
	}

	.policy-content h2 {
		font-size: var(--font-size-xl);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-top: var(--spacing-3xl);
		margin-bottom: var(--spacing-lg);
		padding-bottom: var(--spacing-sm);
		border-bottom: 2px solid var(--color-burnt-orange);
	}

	.policy-content h2:first-of-type {
		margin-top: 0;
	}

	.policy-content h3 {
		font-size: var(--font-size-lg);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-top: var(--spacing-xl);
		margin-bottom: var(--spacing-md);
	}

	.policy-content p {
		font-size: var(--font-size-base);
		line-height: 1.7;
		color: var(--color-gray);
		margin-bottom: var(--spacing-lg);
	}

	.policy-content ul {
		list-style: none;
		padding: 0;
		margin: var(--spacing-lg) 0;
	}

	.policy-content li {
		padding-left: var(--spacing-xl);
		margin-bottom: var(--spacing-md);
		position: relative;
		font-size: var(--font-size-base);
		line-height: 1.6;
		color: var(--color-gray);
	}

	.policy-content li::before {
		content: '•';
		position: absolute;
		left: 0;
		color: var(--color-burnt-orange);
		font-size: 1.5em;
	}

	.policy-content a {
		color: var(--color-burnt-orange);
		text-decoration: none;
		transition: color 0.2s ease;
	}

	.policy-content a:hover {
		color: var(--color-charcoal);
		text-decoration: underline;
	}

	.highlight {
		background: var(--color-cream);
		padding: var(--spacing-lg);
		border-left: 4px solid var(--color-burnt-orange);
		border-radius: 4px;
		margin: var(--spacing-xl) 0;
	}

	.highlight strong {
		color: var(--color-burnt-orange);
	}

	.contact-box {
		background: var(--color-cream);
		padding: var(--spacing-xl);
		border-radius: 8px;
		margin: var(--spacing-xl) 0;
	}

	.contact-box p {
		margin-bottom: var(--spacing-md);
	}

	.contact-box p:last-child {
		margin-bottom: 0;
	}

	.footer-note {
		margin-top: var(--spacing-3xl);
		padding-top: var(--spacing-xl);
		border-top: 1px solid var(--color-light-gray);
		font-style: italic;
		color: var(--color-gray);
	}

	@media (max-width: 768px) {
		.policy-content {
			padding: var(--spacing-xl);
		}
	}
</style>
