// src/app/about/team/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/sections/page-hero";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Our People",
  description:
    "Meet the people behind West Papua Care - conservationists, community organizers, and local leaders working together for marine protection.",
};

const team = [
  {
    name: "Kaspar Elias Anderegg",
    role: "Founder",
    bio: "West Papua Care's founder has lived in Indonesia for 10 years. As an expedition leader, he regularly visits the tribes and wilderness of West Papua, deeply connecting with their cultures. Motivated initially by adventure, Elias has since dedicated himself to humanitarian and conservation efforts to support these communities and ecosystems.",
  },
  {
    name: "Syarif Loji",
    role: "Regional Manager",
    bio: "Born in Misool with both his love for nature and his desire to protect it for future generations. His decade-long partnership with Elias Anderegg and his work as a ranger for the Misool Baseftin MPA has further raised his awareness about global ecological issues and protecting crucial ecosystems.",
  },
];

export default function TeamPage() {
  return (
    <>
      <PageHero
        label="OUR PEOPLE"
        title="Meet the People Behind the Mission"
        subtitle="Combining marine science, community organizing, and traditional knowledge"
      />

      <section className="py-16 lg:py-24 bg-[var(--color-off-white)]">
        <div className="max-w-[var(--max-width-content)] mx-auto px-8">
          {/* Intro Text */}
          <div className="max-w-[800px] mx-auto text-center mb-16">
            <p className="text-lg leading-[1.7] text-[var(--color-gray)]">
              Our team combines on-the-ground conservation experience with deep
              cultural connections to West Papua. We work in close partnership
              with traditional leaders, community members, and the 15-person MPA
              Committee to establish community-led marine protection areas in
              Misool, Raja Ampat.
            </p>
          </div>

          {/* Core Team */}
          <div className="flex flex-col items-center justify-center gap-4">
            <h2 className="text-center mb-12">Core Team</h2>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 mb-24">
              {team.map((member, index) => (
                <div
                  key={index}
                  className="bg-[var(--color-cream)] rounded-lg overflow-hidden transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
                >
                  {/* Photo Placeholder */}
                  <div className="h-[300px] bg-gradient-to-br from-[var(--color-forest-green-deep)] to-[var(--color-forest-green)] flex items-center justify-center">
                    <div className="w-[150px] h-[150px] rounded-full bg-[rgba(255,255,255,0.2)] border-4 border-[var(--color-off-white)]" />
                  </div>
                  {/* Info */}
                  <div className="p-8">
                    <h3 className="mb-1">{member.name}</h3>
                    <div className="text-[var(--color-navy-accent)] font-semibold mb-4">
                      {member.role}
                    </div>
                    <p className="text-[var(--color-gray)] leading-relaxed m-0">
                      {member.bio}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Join Box CTA */}
          <div className="bg-[var(--color-cream)] p-12 lg:p-16 rounded-xl text-center flex flex-col items-center justify-center gap-4 text-balance">
            <div className="section-label text-[var(--color-gray)]">
              [ GET INVOLVED ]
            </div>
            <h2 className="text-center mb-4">
              Join Us in Protecting the Amazon of the Seas
            </h2>
            <p className="text-center text-lg leading-relaxed text-[var(--color-gray)] max-w-[600px] mx-auto mb-8">
              Traditional indigenous governance meets conservation science to
              safeguard the world&apos;s most biodiverse marine ecosystem for
              generations to come
            </p>
            <Button variant="cta" size="lg" asChild>
              <Link href="/get-involved">Support Our Mission</Link>
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}

// src/routes/about/team/+page.svelte
<script lang="ts">
	const team = [
		{
			name: 'Kaspar Elias Anderegg',
			role: 'Founder',
			bio: 'West Papua Care\'s founder has lived in Indonesia for 10 years. As an expedition leader, he regularly visits the tribes and wilderness of West Papua, deeply connecting with their cultures. Motivated initially by adventure, Elias has since dedicated himself to humanitarian and conservation efforts to support these communities and ecosystems.',
			image: '/images/team/elias.jpg'
		},
		{
			name: 'Syarif Loji',
			role: 'Regional Manager',
			bio: 'Born in Misool with both his love for nature and his desire to protect it for future generations. His decade-long partnership with Elias Anderegg and his work as a ranger for the Misool Baseftin MPA has further raised his awareness about global ecological issues and protecting crucial ecosystems.',
			image: '/images/team/syarif.jpg'
		}
	];

	const advisors = [];
</script>

<section class="page-hero">
	<div class="page-hero__container">
		<div class="section-label">[ OUR PEOPLE ]</div>
		<h1 class="page-hero__title">Meet the People Behind the Mission</h1>
		<p class="page-hero__subtitle">
			Combining marine science, community organizing, and traditional knowledge
		</p>
	</div>
</section>

<section class="content-section">
	<div class="content-container">
		<div class="intro-text">
			<p>
				Our team combines on-the-ground conservation experience with deep cultural connections to West Papua. We work in close partnership with traditional leaders, community members, and the 15-person MPA Committee to establish community-led marine protection areas in Misool, Raja Ampat.
			</p>
		</div>

		<h2 class="section-title">Core Team</h2>
		<div class="team-grid">
			{#each team as member}
				<div class="team-card">
					<div class="team-photo">
						<div class="photo-placeholder"></div>
					</div>
					<div class="team-info">
						<h3 class="member-name">{member.name}</h3>
						<div class="member-role">{member.role}</div>
						<p class="member-bio">{member.bio}</p>
					</div>
				</div>
			{/each}
		</div>

		<div class="join-box">
			<div class="section-label">[ GET INVOLVED ]</div>
			<h2>Join Us in Protecting the Amazon of the Seas</h2>
			<p>
				Traditional indigenous governance meets conservation science to safeguard the world's most biodiverse marine ecosystem for generations to come
			</p>
			<a href="/get-involved" class="join-link">Support Our Mission</a>
		</div>
	</div>
</section>

<style>
	.page-hero {
		background: var(--color-forest-green-deep);
		padding: clamp(8rem, 15vh, 12rem) 0 clamp(3rem, 6vh, 5rem);
		position: relative;
	}

	.page-hero::before {
		content: '';
		position: absolute;
		inset: 0;
		opacity: 0.03;
		background-image: radial-gradient(circle at 1px 1px, rgba(255, 255, 255, 0.15) 1px, transparent 1px);
		background-size: 40px 40px;
	}

	.page-hero__container {
		max-width: var(--max-width-content);
		margin: 0 auto;
		padding: 0 var(--spacing-xl);
		position: relative;
		z-index: 1;
		text-align: center;
	}

	.page-hero__title {
		font-size: clamp(2.5rem, 5vw, 4rem);
		font-weight: 700;
		line-height: 1.2;
		color: var(--color-off-white);
		margin-bottom: var(--spacing-lg);
	}

	.page-hero__subtitle {
		font-size: clamp(1.125rem, 2vw, 1.5rem);
		line-height: 1.6;
		color: rgba(255, 255, 255, 0.9);
		max-width: 800px;
		margin: 0 auto;
	}

	.content-section {
		padding: clamp(4rem, 8vh, 6rem) 0;
		background: var(--color-off-white);
	}

	.content-container {
		max-width: var(--max-width-content);
		margin: 0 auto;
		padding: 0 var(--spacing-xl);
	}

	.intro-text {
		max-width: 800px;
		margin: 0 auto var(--spacing-3xl);
		text-align: center;
	}

	.intro-text p {
		font-size: var(--font-size-lg);
		line-height: 1.7;
		color: var(--color-gray);
	}

	.section-title {
		font-size: var(--font-size-2xl);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-2xl);
		text-align: center;
	}

	.team-grid {
		display: grid;
		grid-template-columns: 1fr;
		gap: var(--spacing-2xl);
		margin-bottom: clamp(4rem, 8vh, 6rem);
	}

	.team-card {
		background: var(--color-cream);
		border-radius: 8px;
		overflow: hidden;
		display: grid;
		grid-template-columns: 1fr;
		transition: all 0.3s ease;
	}

	.team-card:hover {
		transform: translateY(-4px);
		box-shadow: var(--shadow-lg);
	}

	.team-photo {
		background: linear-gradient(135deg, var(--color-forest-green-deep) 0%, var(--color-forest-green) 100%);
		height: 300px;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.photo-placeholder {
		width: 150px;
		height: 150px;
		border-radius: 50%;
		background: rgba(255, 255, 255, 0.2);
		border: 4px solid var(--color-off-white);
	}

	.team-info {
		padding: var(--spacing-xl);
	}

	.member-name {
		font-size: var(--font-size-xl);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-xs);
	}

	.member-role {
		font-size: var(--font-size-base);
		font-weight: 600;
		color: var(--color-burnt-orange);
		margin-bottom: var(--spacing-md);
	}

	.member-bio {
		font-size: var(--font-size-base);
		line-height: 1.6;
		color: var(--color-gray);
		margin: 0;
	}

	.advisors-grid {
		display: grid;
		grid-template-columns: 1fr;
		gap: var(--spacing-lg);
		margin-bottom: clamp(4rem, 8vh, 6rem);
	}

	.advisor-card {
		background: var(--color-cream);
		padding: var(--spacing-xl);
		border-radius: 8px;
		border-left: 4px solid var(--color-burnt-orange);
	}

	.advisor-card h4 {
		font-size: var(--font-size-lg);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-xs);
	}

	.advisor-role {
		font-size: var(--font-size-base);
		font-weight: 500;
		color: var(--color-burnt-orange);
		margin-bottom: var(--spacing-xs);
	}

	.advisor-affiliation {
		font-size: var(--font-size-sm);
		color: var(--color-gray);
	}

	.join-box {
		background: var(--color-cream);
		padding: clamp(3rem, 6vh, 5rem) var(--spacing-2xl);
		border-radius: 12px;
		text-align: center;
	}

	.join-box h2 {
		font-size: var(--font-size-2xl);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-md);
	}

	.join-box p {
		font-size: var(--font-size-lg);
		line-height: 1.6;
		color: var(--color-gray);
		max-width: 600px;
		margin: 0 auto var(--spacing-xl);
	}

	.join-link {
		display: inline-block;
		padding: var(--spacing-md) var(--spacing-2xl);
		background: var(--color-burnt-orange);
		color: var(--color-off-white);
		text-decoration: none;
		font-family: var(--font-family-heading);
		font-weight: 600;
		font-size: var(--font-size-lg);
		border-radius: 4px;
		transition: all 0.2s ease;
	}

	.join-link:hover {
		background: #b8580c;
	}

	@media (min-width: 768px) {
		.team-card {
			grid-template-columns: 250px 1fr;
		}

		.team-photo {
			height: auto;
		}

		.advisors-grid {
			grid-template-columns: repeat(2, 1fr);
		}
	}

	@media (min-width: 1024px) {
		.team-grid {
			grid-template-columns: repeat(2, 1fr);
		}

		.team-card {
			grid-template-columns: 1fr;
		}

		.team-photo {
			height: 300px;
		}

		.advisors-grid {
			grid-template-columns: repeat(3, 1fr);
		}
	}
</style>
