// src/lib/components/layout/Header.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let menuOpen = $state(false);
	let scrolled = $state(false);
	let activeDropdown = $state<string | null>(null);

	onMount(() => {
		const handleScroll = () => {
			scrolled = window.scrollY > 20;
		};
		window.addEventListener('scroll', handleScroll);
		return () => window.removeEventListener('scroll', handleScroll);
	});

	function toggleMenu() {
		menuOpen = !menuOpen;
		if (menuOpen) {
			document.body.style.overflow = 'hidden';
		} else {
			document.body.style.overflow = 'auto';
		}
	}

	function closeMenu() {
		menuOpen = false;
		document.body.style.overflow = 'auto';
	}

	function toggleDropdown(dropdown: string) {
		activeDropdown = activeDropdown === dropdown ? null : dropdown;
	}

	const navigation = [
		{ href: '/', label: 'HOME' },
		{
			label: 'ABOUT',
			dropdown: [
				{ href: '/about', label: 'Our Story' },
				{ href: '/about/team', label: 'Our People' }
			]
		},
		{
			label: 'PROJECT',
			dropdown: [
				{ href: '/project', label: 'Project Overview' },
				{ href: '/approach', label: 'Our Approach' },
				{ href: '/impact', label: 'Impact Framework' }
			]
		},
		{ href: '/news', label: 'BLOG' },
		{ href: '/get-involved', label: 'GET INVOLVED' },
		{ href: '/contact', label: 'DONATE', isDonate: true }
	];
</script>

<header class="header {scrolled ? 'scrolled' : ''}">
	<div class="header__container">
		<!-- Logo -->
		<a href="/" class="header__logo" aria-label="West Papua Care Home">
			<img src="/logo.png" alt="West Papua Care" class="logo" />
		</a>

		<!-- Desktop Navigation -->
		<nav class="desktop-nav" aria-label="Main navigation">
			{#each navigation as item}
				{#if item.dropdown}
					<div class="nav-item nav-item--dropdown">
						<button
							class="nav-link"
							onclick={() => toggleDropdown(item.label)}
							aria-expanded={activeDropdown === item.label}
						>
							{item.label}
							<svg class="dropdown-icon {activeDropdown === item.label ? 'open' : ''}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
								<polyline points="6 9 12 15 18 9"></polyline>
							</svg>
						</button>
						{#if activeDropdown === item.label}
							<div class="dropdown-menu">
								{#each item.dropdown as subItem}
									<a href={subItem.href} class="dropdown-link">{subItem.label}</a>
								{/each}
							</div>
						{/if}
					</div>
				{:else}
					<a href={item.href} class="nav-link {item.isDonate ? 'nav-link--donate' : ''}">{item.label}</a>
				{/if}
			{/each}
		</nav>

		<!-- Mobile Menu Toggle -->
		<button
			class="mobile-toggle"
			aria-label="Toggle menu"
			aria-expanded={menuOpen}
			onclick={toggleMenu}
		>
			<span class="hamburger-line {menuOpen ? 'open' : ''}"></span>
			<span class="hamburger-line {menuOpen ? 'open' : ''}"></span>
			<span class="hamburger-line {menuOpen ? 'open' : ''}"></span>
		</button>
	</div>

	<!-- Mobile Menu -->
	{#if menuOpen}
		<div class="mobile-menu">
			<nav class="mobile-nav" aria-label="Mobile navigation">
				{#each navigation as item, index}
					{#if item.dropdown}
						<div class="mobile-nav-group">
							<div class="mobile-nav-label">{item.label}</div>
							{#each item.dropdown as subItem}
								<a href={subItem.href} class="mobile-nav-link" onclick={closeMenu}>
									{subItem.label}
								</a>
							{/each}
						</div>
					{:else}
						<a href={item.href} class="mobile-nav-link {item.isDonate ? 'mobile-nav-link--donate' : ''}" onclick={closeMenu}>
							{item.label}
						</a>
					{/if}
				{/each}
			</nav>
		</div>
	{/if}
</header>

<style>
	.header {
		position: fixed;
		top: 0;
		width: 100%;
		background: var(--color-forest-green-deep);
		transition: all 0.3s ease;
		z-index: var(--z-sticky);
	}

	.header.scrolled {
		background: rgba(31, 39, 32, 0.98);
		backdrop-filter: blur(12px);
		box-shadow: var(--shadow-md);
	}

	.header__container {
		max-width: var(--max-width-wide);
		margin: 0 auto;
		padding: var(--spacing-md) var(--spacing-xl);
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: var(--spacing-2xl);
	}

	.header__logo {
		text-decoration: none;
		display: flex;
		align-items: center;
		z-index: 10;
	}

	.logo {
		height: 36px;
		width: auto;
		filter: brightness(0) invert(1);
	}

	/* Desktop Navigation */
	.desktop-nav {
		display: none;
		flex: 1;
		justify-content: flex-end;
		align-items: center;
		gap: var(--spacing-lg);
	}

	.nav-item {
		position: relative;
	}

	.nav-link {
		font-family: var(--font-family-heading);
		font-size: 0.875rem;
		font-weight: 500;
		letter-spacing: 0.05em;
		color: var(--color-off-white);
		text-decoration: none;
		background: none;
		border: none;
		padding: var(--spacing-sm) var(--spacing-md);
		cursor: pointer;
		transition: color 0.3s ease;
		display: flex;
		align-items: center;
		gap: var(--spacing-xs);
		white-space: nowrap;
	}

	.nav-link:hover {
		color: var(--color-burnt-orange);
	}

	.nav-link--donate {
		background: var(--color-burnt-orange);
		color: var(--color-off-white);
		border-radius: 4px;
		padding: var(--spacing-sm) var(--spacing-lg);
		font-weight: 600;
	}

	.nav-link--donate:hover {
		background: #b8580c;
		color: var(--color-off-white);
	}

	.dropdown-icon {
		width: 16px;
		height: 16px;
		transition: transform 0.3s ease;
	}

	.dropdown-icon.open {
		transform: rotate(180deg);
	}

	.dropdown-menu {
		position: absolute;
		top: 100%;
		left: 0;
		min-width: 200px;
		background: var(--color-off-white);
		border-radius: 8px;
		box-shadow: var(--shadow-lg);
		padding: var(--spacing-sm);
		margin-top: var(--spacing-sm);
		animation: dropdown-appear 0.2s ease-out;
	}

	.dropdown-link {
		display: block;
		padding: var(--spacing-sm) var(--spacing-md);
		font-size: 0.875rem;
		color: var(--color-charcoal);
		text-decoration: none;
		border-radius: 4px;
		transition: all 0.2s ease;
	}

	.dropdown-link:hover {
		background: var(--color-cream);
		color: var(--color-burnt-orange);
	}

	/* Mobile Toggle */
	.mobile-toggle {
		display: flex;
		flex-direction: column;
		justify-content: center;
		gap: 6px;
		width: 32px;
		height: 32px;
		padding: 0;
		background: none;
		border: none;
		cursor: pointer;
		z-index: 10;
	}

	.hamburger-line {
		width: 100%;
		height: 2px;
		background: var(--color-off-white);
		border-radius: 2px;
		transition: all 0.3s ease;
	}

	.hamburger-line.open:nth-child(1) {
		transform: translateY(8px) rotate(45deg);
	}

	.hamburger-line.open:nth-child(2) {
		opacity: 0;
	}

	.hamburger-line.open:nth-child(3) {
		transform: translateY(-8px) rotate(-45deg);
	}

	/* Mobile Menu */
	.mobile-menu {
		position: fixed;
		top: 64px;
		left: 0;
		right: 0;
		bottom: 0;
		background: var(--color-off-white);
		padding: var(--spacing-xl);
		overflow-y: auto;
		animation: slide-down 0.3s ease-out;
	}

	.mobile-nav {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-md);
	}

	.mobile-nav-group {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-sm);
	}

	.mobile-nav-label {
		font-family: var(--font-family-heading);
		font-size: 0.75rem;
		font-weight: 600;
		letter-spacing: 0.1em;
		color: var(--color-gray);
		padding: var(--spacing-sm) 0;
	}

	.mobile-nav-link {
		display: block;
		padding: var(--spacing-md);
		font-size: var(--font-size-base);
		color: var(--color-charcoal);
		text-decoration: none;
		border-radius: 8px;
		transition: all 0.2s ease;
	}

	.mobile-nav-link:hover {
		background: var(--color-cream);
		color: var(--color-burnt-orange);
	}

	.mobile-nav-link--donate {
		background: var(--color-burnt-orange);
		color: var(--color-off-white);
		font-weight: 600;
		text-align: center;
	}

	.mobile-nav-link--donate:hover {
		background: #b8580c;
		color: var(--color-off-white);
	}

	/* Animations */
	@keyframes dropdown-appear {
		from {
			opacity: 0;
			transform: translateY(-10px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	@keyframes slide-down {
		from {
			opacity: 0;
			transform: translateY(-20px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	/* Desktop */
	@media (min-width: 1024px) {
		.desktop-nav {
			display: flex;
		}

		.mobile-toggle {
			display: none;
		}

		.header__container {
			padding: var(--spacing-lg) var(--spacing-2xl);
		}
	}
</style>

// src/components/layout/header.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import { ChevronDown } from "lucide-react";
import { navigation } from "@/lib/data/navigation";
import { cn } from "@/lib/utils";

export function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [activeDropdown, setActiveDropdown] = useState<string | null>(null);

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 20);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  function toggleMenu() {
    setMenuOpen(!menuOpen);
    if (!menuOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "auto";
    }
  }

  function closeMenu() {
    setMenuOpen(false);
    document.body.style.overflow = "auto";
  }

  function toggleDropdown(dropdown: string) {
    setActiveDropdown(activeDropdown === dropdown ? null : dropdown);
  }

  return (
    <header
      className={cn(
        "fixed top-0 w-full z-[1020] transition-all duration-300",
        scrolled
          ? "bg-[rgba(31,39,32,0.98)] backdrop-blur-[12px] shadow-md"
          : "bg-[var(--color-forest-green-deep)]"
      )}
    >
      <div className="max-w-[var(--max-width-wide)] mx-auto px-6 lg:px-12 py-4 lg:py-6 flex items-center justify-between gap-12">
        {/* Logo */}
        <Link
          href="/"
          className="no-underline flex items-center z-10"
          aria-label="West Papua Care Home"
        >
          <Image
            src="/logo.png"
            alt="West Papua Care"
            width={120}
            height={36}
            className="h-9 w-auto brightness-0 invert"
            priority
          />
        </Link>

        {/* Desktop Navigation */}
        <nav
          className="hidden lg:flex flex-1 justify-end items-center gap-6"
          aria-label="Main navigation"
        >
          {navigation.map((item) =>
            item.dropdown ? (
              <div key={item.label} className="relative">
                <button
                  onClick={() => toggleDropdown(item.label)}
                  aria-expanded={activeDropdown === item.label}
                  className="font-[var(--font-family-heading)] text-sm font-medium tracking-wide text-white text-[var(--color-off-white)] bg-transparent border-none py-2 px-4 cursor-pointer transition-colors duration-300 flex items-center gap-1 whitespace-nowrap hover:text-orange-500 hover:text-[var(--color-burnt-orange)]"
                >
                  {item.label}
                  <ChevronDown
                    className={cn(
                      "w-4 h-4 transition-transform duration-300",
                      activeDropdown === item.label && "rotate-180"
                    )}
                  />
                </button>
                {activeDropdown === item.label && (
                  <div className="absolute top-full left-0 min-w-[200px] bg-[var(--color-off-white)] rounded-lg shadow-lg p-2 mt-2 animate-[dropdown-appear_0.2s_ease-out]">
                    {item.dropdown.map((subItem) => (
                      <Link
                        key={subItem.href}
                        href={subItem.href}
                        className="block py-2 px-4 text-sm text-[var(--color-charcoal)] no-underline rounded transition-all duration-200 hover:bg-[var(--color-cream)] hover:text-[var(--color-burnt-orange)]"
                        onClick={() => setActiveDropdown(null)}
                      >
                        {subItem.label}
                      </Link>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              <Link
                key={item.href}
                href={item.href!}
                className={cn(
                  "font-[var(--font-family-heading)] text-sm font-medium tracking-wide text-white text-[var(--color-off-white)] no-underline py-2 px-4 transition-colors duration-300 whitespace-nowrap hover:text-orange-500 hover:text-[var(--color-burnt-orange)]",
                  item.isDonate &&
                    "bg-orange-600 bg-[var(--color-burnt-orange)] rounded px-6 font-semibold hover:bg-orange-700 hover:bg-[#b8580c] hover:text-white hover:text-[var(--color-off-white)]"
                )}
              >
                {item.label}
              </Link>
            )
          )}
        </nav>

        {/* Mobile Menu Toggle */}
        <button
          className="lg:hidden flex flex-col justify-center gap-1.5 w-8 h-8 p-0 bg-transparent border-none cursor-pointer z-10"
          aria-label="Toggle menu"
          aria-expanded={menuOpen}
          onClick={toggleMenu}
        >
          <span
            className={cn(
              "w-full h-0.5 bg-[var(--color-off-white)] rounded transition-all duration-300",
              menuOpen && "translate-y-2 rotate-45"
            )}
          />
          <span
            className={cn(
              "w-full h-0.5 bg-[var(--color-off-white)] rounded transition-all duration-300",
              menuOpen && "opacity-0"
            )}
          />
          <span
            className={cn(
              "w-full h-0.5 bg-[var(--color-off-white)] rounded transition-all duration-300",
              menuOpen && "-translate-y-2 -rotate-45"
            )}
          />
        </button>
      </div>

      {/* Mobile Menu */}
      {menuOpen && (
        <div className="lg:hidden fixed top-16 left-0 right-0 bottom-0 bg-[var(--color-off-white)] p-8 overflow-y-auto animate-[slide-down_0.3s_ease-out]">
          <nav className="flex flex-col gap-4" aria-label="Mobile navigation">
            {navigation.map((item) =>
              item.dropdown ? (
                <div key={item.label} className="flex flex-col gap-2">
                  <div className="font-[var(--font-family-heading)] text-xs font-semibold tracking-widest text-[var(--color-gray)] py-2">
                    {item.label}
                  </div>
                  {item.dropdown.map((subItem) => (
                    <Link
                      key={subItem.href}
                      href={subItem.href}
                      className="block p-4 text-lg text-[var(--color-charcoal)] no-underline rounded-lg transition-all duration-200 hover:bg-[var(--color-cream)] hover:text-[var(--color-burnt-orange)]"
                      onClick={closeMenu}
                    >
                      {subItem.label}
                    </Link>
                  ))}
                </div>
              ) : (
                <Link
                  key={item.href}
                  href={item.href!}
                  className={cn(
                    "block p-4 text-lg text-[var(--color-charcoal)] no-underline rounded-lg transition-all duration-200 hover:bg-[var(--color-cream)] hover:text-[var(--color-burnt-orange)]",
                    item.isDonate &&
                      "bg-[var(--color-burnt-orange)] text-[var(--color-off-white)] font-semibold text-center hover:bg-[#b8580c] hover:text-[var(--color-off-white)]"
                  )}
                  onClick={closeMenu}
                >
                  {item.label}
                </Link>
              )
            )}
          </nav>
        </div>
      )}
    </header>
  );
}
