// src/routes/project/+page.svelte
<script lang="ts">
	import Button from '$lib/components/ui/Button.svelte';
</script>

<section class="page-hero">
	<div class="page-hero__container">
		<div class="section-label">[ PROJECT OVERVIEW ]</div>
		<h1 class="page-hero__title">Community-Led Marine Protected Area</h1>
		<p class="page-hero__subtitle">
			Establishing a 250 km² no-take zone in Misool, Raja Ampat through traditional governance and modern conservation science
		</p>
	</div>
</section>

<section class="content-section">
	<div class="content-container">
		<div class="content-grid">
			<div class="content-main">
				<h2>The Vision</h2>
				<p>
					West Papua Care is establishing a groundbreaking community-led Marine Protected Area in Misool, Raja Ampat, Indonesia—the heart of the Coral Triangle and the most biodiverse marine ecosystem on Earth. This 250 km² no-take zone covers the islands and archipelagos of Damu, Canpade, Balbulol, Sagof, Efpian, Kasiah, and surrounding waters—an area twice the size of Paris city.
				</p>

				<h2>Why Misool, Raja Ampat</h2>
				<p>
					Misool is a biodiversity hotspot within Raja Ampat, home to 75% of the world's coral species and over 1,600 fish species. Its fringing reefs, reef walls, atolls, off-shore reefs, caves and underwater rock formations host huge marine biodiversity including endemic and key species. It is an important spawning ground for corals and fishes.
				</p>
				<p>
					The area faces serious threats from cyanide fishing, illegal fishers from as far as Sulawesi, sea turtle harvesting, shark finning, and past bomb fishing damage. With strong community consensus already secured and traditional leaders endorsing the project, we have a unique window of opportunity to protect this marine treasure before it's too late.
				</p>

				<h2>Project Goals</h2>
				<ul class="styled-list">
					<li>Establish 250 km² no-take zone Marine Protected Area with 10km buffer zone</li>
					<li>Restore traditional governance systems (adat/sasi) for marine management</li>
					<li>Target 50% increase in fish biomass within 5 years based on regional MPA performance data</li>
					<li>Protect key species: Napoleon wrasse, Hawksbill and Green sea turtles, Bumphead Parrotfish, and shark species</li>
					<li>Create sustainable livelihoods through ecotourism and resource management</li>
					<li>Conduct GPS-marked scientific surveys of coral health and ecosystem dynamics</li>
					<li>IUCN Red List species identification and conservation status tracking</li>
					<li>Establish base camp operations on Cempedak Island with ranger patrols</li>
				</ul>

				<h2>Timeline</h2>
				<div class="timeline-simple">
					<div class="timeline-item">
						<strong>2023-2024:</strong> Community consultations, baseline surveys, and governance framework establishment
					</div>
					<div class="timeline-item">
						<strong>2024-2025:</strong> MPA Committee formation, patrol systems, and monitoring protocols
					</div>
					<div class="timeline-item">
						<strong>2025+:</strong> Official designation, ongoing monitoring, and benefit sharing programs
					</div>
				</div>

				<h2>Impact to Date</h2>
				<div class="impact-highlights">
					<div class="highlight-stat">
						<div class="stat-value">250 km²</div>
						<div class="stat-label">Marine area under community protection</div>
					</div>
					<div class="highlight-stat">
						<div class="stat-value">10+</div>
						<div class="stat-label">Villages with strong consensus</div>
					</div>
					<div class="highlight-stat">
						<div class="stat-value">15</div>
						<div class="stat-label">Monitoring sites established</div>
					</div>
					<div class="highlight-stat">
						<div class="stat-value">12</div>
						<div class="stat-label">Community members Reef Check certified</div>
					</div>
				</div>

				<div class="cta-box">
					<h3>Get Involved</h3>
					<p>Join us in protecting the Amazon of the Seas through community-led conservation.</p>
					<Button variant="cta" size="md" href="/get-involved">Support This Project</Button>
				</div>
			</div>

			<aside class="content-sidebar">
				<div class="info-card">
					<h3>Quick Facts</h3>
					<dl class="fact-list">
						<dt>Location</dt>
						<dd>Misool, Raja Ampat, West Papua, Indonesia</dd>

						<dt>Specific Islands</dt>
						<dd>Damu, Canpade, Balbulol, Sagof, Efpian, Kasiah</dd>

						<dt>Area</dt>
						<dd>250 km² (no-take zone with 10km buffer)</dd>

						<dt>Base Camp</dt>
						<dd>Cempedak Island</dd>

						<dt>Communities</dt>
						<dd>10+ villages engaged</dd>

						<dt>Biodiversity</dt>
						<dd>75% of world's coral species<br>1,600+ fish species</dd>

						<dt>Governance</dt>
						<dd>Community-led with traditional leaders</dd>

						<dt>Status</dt>
						<dd>Implementation phase (October 2025)</dd>
					</dl>
				</div>
			</aside>
		</div>
	</div>
</section>

<style>
	.page-hero {
		background: var(--color-forest-green-deep);
		padding: clamp(8rem, 15vh, 12rem) 0 clamp(3rem, 6vh, 5rem);
		position: relative;
	}

	.page-hero::before {
		content: '';
		position: absolute;
		inset: 0;
		opacity: 0.03;
		background-image: radial-gradient(circle at 1px 1px, rgba(255, 255, 255, 0.15) 1px, transparent 1px);
		background-size: 40px 40px;
	}

	.page-hero__container {
		max-width: var(--max-width-content);
		margin: 0 auto;
		padding: 0 var(--spacing-xl);
		position: relative;
		z-index: 1;
		text-align: center;
	}

	.page-hero__title {
		font-size: clamp(2.5rem, 5vw, 4rem);
		font-weight: 700;
		line-height: 1.2;
		color: var(--color-off-white);
		margin-bottom: var(--spacing-lg);
	}

	.page-hero__subtitle {
		font-size: clamp(1.125rem, 2vw, 1.5rem);
		line-height: 1.6;
		color: rgba(255, 255, 255, 0.9);
		max-width: 800px;
		margin: 0 auto;
	}

	.content-section {
		padding: clamp(4rem, 8vh, 6rem) 0;
		background: var(--color-off-white);
	}

	.content-container {
		max-width: var(--max-width-content);
		margin: 0 auto;
		padding: 0 var(--spacing-xl);
	}

	.content-grid {
		display: grid;
		grid-template-columns: 1fr;
		gap: var(--spacing-3xl);
	}

	.content-main h2 {
		font-size: var(--font-size-2xl);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-top: var(--spacing-3xl);
		margin-bottom: var(--spacing-lg);
	}

	.content-main h2:first-child {
		margin-top: 0;
	}

	.content-main p {
		font-size: var(--font-size-base);
		line-height: 1.7;
		color: var(--color-gray);
		margin-bottom: var(--spacing-lg);
	}

	.styled-list {
		list-style: none;
		padding: 0;
		margin: var(--spacing-lg) 0;
	}

	.styled-list li {
		padding-left: var(--spacing-xl);
		margin-bottom: var(--spacing-md);
		position: relative;
		font-size: var(--font-size-base);
		line-height: 1.6;
		color: var(--color-gray);
	}

	.styled-list li::before {
		content: '•';
		position: absolute;
		left: 0;
		color: var(--color-burnt-orange);
		font-size: 1.5em;
	}

	.timeline-simple {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-lg);
		margin: var(--spacing-xl) 0;
	}

	.timeline-item {
		padding: var(--spacing-lg);
		background: var(--color-cream);
		border-left: 4px solid var(--color-burnt-orange);
		border-radius: 4px;
		font-size: var(--font-size-base);
		line-height: 1.6;
		color: var(--color-gray);
	}

	.timeline-item strong {
		color: var(--color-charcoal);
		display: block;
		margin-bottom: var(--spacing-xs);
	}

	.impact-highlights {
		display: grid;
		grid-template-columns: 1fr;
		gap: var(--spacing-lg);
		margin: var(--spacing-xl) 0;
	}

	.highlight-stat {
		background: var(--color-cream);
		padding: var(--spacing-xl);
		border-radius: 8px;
		text-align: center;
		border: 2px solid var(--color-burnt-orange);
	}

	.stat-value {
		font-family: var(--font-family-heading);
		font-size: clamp(2rem, 4vw, 3rem);
		font-weight: 700;
		color: var(--color-burnt-orange);
		margin-bottom: var(--spacing-sm);
	}

	.stat-label {
		font-size: var(--font-size-base);
		color: var(--color-gray);
		line-height: 1.5;
	}

	.cta-box {
		background: var(--color-cream);
		padding: var(--spacing-2xl);
		border-radius: 8px;
		text-align: center;
		margin-top: var(--spacing-3xl);
	}

	.cta-box h3 {
		font-size: var(--font-size-xl);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-md);
	}

	.cta-box p {
		margin-bottom: var(--spacing-lg);
	}

	.content-sidebar {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-xl);
	}

	.info-card {
		background: var(--color-cream);
		padding: var(--spacing-xl);
		border-radius: 8px;
	}

	.info-card h3 {
		font-size: var(--font-size-lg);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-lg);
	}

	.fact-list {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-md);
	}

	.fact-list dt {
		font-family: var(--font-family-heading);
		font-size: var(--font-size-sm);
		font-weight: 600;
		color: var(--color-burnt-orange);
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.fact-list dd {
		font-size: var(--font-size-base);
		color: var(--color-gray);
		margin: 0 0 var(--spacing-md) 0;
		line-height: 1.5;
	}

	.link-list {
		list-style: none;
		padding: 0;
		margin: 0;
		display: flex;
		flex-direction: column;
		gap: var(--spacing-sm);
	}

	.link-list a {
		display: block;
		padding: var(--spacing-sm) var(--spacing-md);
		color: var(--color-charcoal);
		text-decoration: none;
		border-radius: 4px;
		transition: all 0.2s ease;
		font-size: var(--font-size-base);
	}

	.link-list a:hover {
		background: var(--color-off-white);
		color: var(--color-burnt-orange);
	}

	@media (min-width: 768px) {
		.impact-highlights {
			grid-template-columns: repeat(2, 1fr);
		}
	}

	@media (min-width: 1024px) {
		.content-grid {
			grid-template-columns: 2fr 1fr;
		}

		.impact-highlights {
			grid-template-columns: repeat(4, 1fr);
		}
	}
</style>

// src/app/project/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/sections/page-hero";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Project Overview",
  description:
    "Learn about our community-led Marine Protected Area in Misool, Raja Ampat - a 250 km² no-take zone protecting the world's most biodiverse coral reefs.",
};

const goals = [
  "Establish 250 km² no-take zone Marine Protected Area with 10km buffer zone",
  "Restore traditional governance systems (adat/sasi) for marine management",
  "Target 50% increase in fish biomass within 5 years based on regional MPA performance data",
  "Protect key species: Napoleon wrasse, Hawksbill and Green sea turtles, Bumphead Parrotfish, and shark species",
  "Create sustainable livelihoods through ecotourism and resource management",
  "Conduct GPS-marked scientific surveys of coral health and ecosystem dynamics",
  "IUCN Red List species identification and conservation status tracking",
  "Establish base camp operations on Cempedak Island with ranger patrols",
];

const stats = [
  { value: "250 km²", label: "Marine area under community protection" },
  { value: "10+", label: "Villages with strong consensus" },
  { value: "15", label: "Monitoring sites established" },
  { value: "12", label: "Community members Reef Check certified" },
];

export default function ProjectPage() {
  return (
    <>
      <PageHero
        label="PROJECT OVERVIEW"
        title="Community-Led Marine Protected Area"
        subtitle="Establishing a 250 km² no-take zone in Misool, Raja Ampat through traditional governance and modern conservation science"
      />

      <section className="py-16 lg:py-24 bg-[var(--color-off-white)]">
        <div className="max-w-[var(--max-width-content)] mx-auto px-8">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
            <div className="lg:col-span-2">
              <h2 className="text-3xl font-semibold text-[var(--color-charcoal)] mb-6">
                The Vision
              </h2>
              <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
                West Papua Care is establishing a groundbreaking community-led
                Marine Protected Area in Misool, Raja Ampat, Indonesia—the heart
                of the Coral Triangle and the most biodiverse marine ecosystem
                on Earth. This 250 km² no-take zone covers the islands and
                archipelagos of Damu, Canpade, Balbulol, Sagof, Efpian, Kasiah,
                and surrounding waters—an area twice the size of Paris city.
              </p>

              <h2 className="text-3xl font-semibold text-[var(--color-charcoal)] mt-12 mb-6">
                Why Misool, Raja Ampat
              </h2>
              <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
                Misool is a biodiversity hotspot within Raja Ampat, home to 75%
                of the world&apos;s coral species and over 1,600 fish species.
                Its fringing reefs, reef walls, atolls, off-shore reefs, caves
                and underwater rock formations host huge marine biodiversity
                including endemic and key species. It is an important spawning
                ground for corals and fishes.
              </p>
              <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
                The area faces serious threats from cyanide fishing, illegal
                fishers from as far as Sulawesi, sea turtle harvesting, shark
                finning, and past bomb fishing damage. With strong community
                consensus already secured and traditional leaders endorsing the
                project, we have a unique window of opportunity to protect this
                marine treasure before it&apos;s too late.
              </p>

              <h2 className="text-3xl font-semibold text-[var(--color-charcoal)] mt-12 mb-6">
                Project Goals
              </h2>
              <ul className="list-none p-0 my-6">
                {goals.map((goal, index) => (
                  <li
                    key={index}
                    className="pl-8 mb-4 relative text-lg leading-relaxed text-[var(--color-gray)] before:content-['•'] before:absolute before:left-0 before:text-[var(--color-burnt-orange)] before:text-[1.5em]"
                  >
                    {goal}
                  </li>
                ))}
              </ul>

              <h2 className="text-3xl font-semibold text-[var(--color-charcoal)] mt-12 mb-6">
                Timeline
              </h2>
              <div className="flex flex-col gap-6 my-8">
                <div className="p-6 bg-[var(--color-cream)] border-l-4 border-[var(--color-burnt-orange)] rounded">
                  <strong className="block text-[var(--color-charcoal)] mb-2">
                    2023-2024:
                  </strong>
                  <span className="text-[var(--color-gray)]">
                    Community consultations, baseline surveys, and governance
                    framework establishment
                  </span>
                </div>
                <div className="p-6 bg-[var(--color-cream)] border-l-4 border-[var(--color-burnt-orange)] rounded">
                  <strong className="block text-[var(--color-charcoal)] mb-2">
                    2024-2025:
                  </strong>
                  <span className="text-[var(--color-gray)]">
                    MPA Committee formation, patrol systems, and monitoring
                    protocols
                  </span>
                </div>
                <div className="p-6 bg-[var(--color-cream)] border-l-4 border-[var(--color-burnt-orange)] rounded">
                  <strong className="block text-[var(--color-charcoal)] mb-2">
                    2025+:
                  </strong>
                  <span className="text-[var(--color-gray)]">
                    Official designation, ongoing monitoring, and benefit
                    sharing programs
                  </span>
                </div>
              </div>

              <h2 className="text-3xl font-semibold text-[var(--color-charcoal)] mt-12 mb-6">
                Impact to Date
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 my-8">
                {stats.map((stat, index) => (
                  <div
                    key={index}
                    className="bg-[var(--color-cream)] p-8 rounded-lg text-center border-2 border-[var(--color-burnt-orange)]"
                  >
                    <div className="font-[var(--font-family-heading)] text-[clamp(2rem,4vw,3rem)] font-bold text-[var(--color-burnt-orange)] mb-2">
                      {stat.value}
                    </div>
                    <div className="text-lg text-[var(--color-gray)] leading-[1.5]">
                      {stat.label}
                    </div>
                  </div>
                ))}
              </div>

              <div className="bg-[var(--color-cream)] p-12 rounded-lg text-center mt-12">
                <h3 className="text-2xl font-semibold text-[var(--color-charcoal)] mb-4">
                  Get Involved
                </h3>
                <p className="text-lg text-[var(--color-gray)] mb-6">
                  Join us in protecting the Amazon of the Seas through
                  community-led conservation.
                </p>
                <Button variant="cta" size="md" asChild>
                  <Link href="/get-involved">Support This Project</Link>
                </Button>
              </div>
            </div>

            <aside className="flex flex-col gap-8">
              <div className="bg-[var(--color-cream)] p-8 rounded-lg">
                <h3 className="text-2xl font-semibold text-[var(--color-charcoal)] mb-6">
                  Quick Facts
                </h3>
                <dl className="flex flex-col gap-4">
                  <dt className="font-[var(--font-family-heading)] text-sm font-semibold text-[var(--color-burnt-orange)] uppercase tracking-wide">
                    Location
                  </dt>
                  <dd className="text-lg text-[var(--color-gray)] mb-4 leading-[1.5]">
                    Misool, Raja Ampat, West Papua, Indonesia
                  </dd>

                  <dt className="font-[var(--font-family-heading)] text-sm font-semibold text-[var(--color-burnt-orange)] uppercase tracking-wide">
                    Specific Islands
                  </dt>
                  <dd className="text-lg text-[var(--color-gray)] mb-4 leading-[1.5]">
                    Damu, Canpade, Balbulol, Sagof, Efpian, Kasiah
                  </dd>

                  <dt className="font-[var(--font-family-heading)] text-sm font-semibold text-[var(--color-burnt-orange)] uppercase tracking-wide">
                    Area
                  </dt>
                  <dd className="text-lg text-[var(--color-gray)] mb-4 leading-[1.5]">
                    250 km² (no-take zone with 10km buffer)
                  </dd>

                  <dt className="font-[var(--font-family-heading)] text-sm font-semibold text-[var(--color-burnt-orange)] uppercase tracking-wide">
                    Base Camp
                  </dt>
                  <dd className="text-lg text-[var(--color-gray)] mb-4 leading-[1.5]">
                    Cempedak Island
                  </dd>

                  <dt className="font-[var(--font-family-heading)] text-sm font-semibold text-[var(--color-burnt-orange)] uppercase tracking-wide">
                    Communities
                  </dt>
                  <dd className="text-lg text-[var(--color-gray)] mb-4 leading-[1.5]">
                    10+ villages engaged
                  </dd>

                  <dt className="font-[var(--font-family-heading)] text-sm font-semibold text-[var(--color-burnt-orange)] uppercase tracking-wide">
                    Biodiversity
                  </dt>
                  <dd className="text-lg text-[var(--color-gray)] mb-4 leading-[1.5]">
                    75% of world&apos;s coral species
                    <br />
                    1,600+ fish species
                  </dd>

                  <dt className="font-[var(--font-family-heading)] text-sm font-semibold text-[var(--color-burnt-orange)] uppercase tracking-wide">
                    Governance
                  </dt>
                  <dd className="text-lg text-[var(--color-gray)] mb-4 leading-[1.5]">
                    Community-led with traditional leaders
                  </dd>

                  <dt className="font-[var(--font-family-heading)] text-sm font-semibold text-[var(--color-burnt-orange)] uppercase tracking-wide">
                    Status
                  </dt>
                  <dd className="text-lg text-[var(--color-gray)] leading-[1.5]">
                    Implementation phase (October 2025)
                  </dd>
                </dl>
              </div>
            </aside>
          </div>
        </div>
      </section>
    </>
  );
}
