// src/app/approach/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/sections/page-hero";
import { Button } from "@/components/ui/button";
import {
  Users,
  FileSearch,
  Shield,
  TrendingUp,
  Handshake,
  Scale,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Our Approach",
  description:
    "Learn about our community-led conservation approach - combining traditional governance with modern science for effective marine protection.",
};

const principles = [
  {
    icon: Users,
    title: "Community First",
    description:
      "Local communities lead decision-making. We follow rigorous Free, Prior and Informed Consent (FPIC) protocols, ensuring genuine ownership rather than token participation.",
  },
  {
    icon: FileSearch,
    title: "Evidence-Based",
    description:
      "Quarterly monitoring tracks coral health, fish biomass, and species diversity. We adapt our approach based on what the data tells us, not assumptions.",
  },
  {
    icon: Shield,
    title: "Traditional Governance",
    description:
      "We integrate adat (customary law) and sasi (seasonal closures) with modern MPA structures. Traditional systems aren't obstacles—they're foundations.",
  },
  {
    icon: TrendingUp,
    title: "Sustainable Financing",
    description:
      "We build diverse revenue streams—ecotourism, sustainable fishing licensing, carbon credits—so conservation continues after external funding ends.",
  },
  {
    icon: Handshake,
    title: "Benefit Sharing",
    description:
      "Conservation must improve livelihoods. Revenue sharing ensures communities see tangible benefits from protection, creating positive incentives.",
  },
  {
    icon: Scale,
    title: "Transparent Governance",
    description:
      "MPA Committee includes community representatives, traditional leaders, and technical advisors. All decisions are documented and publicly shared.",
  },
];

const methodology = [
  {
    phase: "Phase 1",
    title: "Community Engagement",
    description:
      "Build relationships with traditional leaders and communities. Conduct FPIC consultations across all affected villages. Document traditional knowledge and governance systems.",
    status: "Completed",
  },
  {
    phase: "Phase 2",
    title: "Baseline Assessment",
    description:
      "Scientific surveys of coral reef health, fish populations, and key species. GPS mapping of boundaries and zones. Community resource mapping workshops.",
    status: "Completed",
  },
  {
    phase: "Phase 3",
    title: "Governance Framework",
    description:
      "Establish MPA Committee with community representation. Define zones (no-take, sustainable use, buffer). Create patrol protocols and enforcement procedures.",
    status: "In Progress",
  },
  {
    phase: "Phase 4",
    title: "Implementation",
    description:
      "Deploy ranger patrols and monitoring systems. Establish base camp operations. Begin quarterly scientific monitoring. Launch community benefit programs.",
    status: "Starting October 2025",
  },
  {
    phase: "Phase 5",
    title: "Monitoring & Adaptation",
    description:
      "Track ecosystem recovery and compliance rates. Adjust management based on data. Expand successful programs. Share learnings with other communities.",
    status: "Ongoing",
  },
];

export default function ApproachPage() {
  return (
    <>
      <PageHero
        label="OUR APPROACH"
        title="Community-Led Conservation"
        subtitle="Combining traditional governance with modern science for effective, lasting marine protection"
      />

      <section className="py-16 lg:py-24 bg-[var(--color-off-white)]">
        <div className="max-w-[var(--max-width-content)] mx-auto px-8">
          <div className="max-w-[900px] mx-auto">
            <h2 className="text-3xl font-semibold text-[var(--color-charcoal)] mb-6">
              Why Community-Led?
            </h2>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-6">
              Traditional top-down Marine Protected Areas often fail because
              they exclude the very people whose cooperation is essential for
              success. When communities feel alienated from conservation
              decisions, compliance drops and conflict rises.
            </p>
            <p className="text-lg leading-[1.7] text-[var(--color-gray)] mb-12">
              Our approach inverts this model. Communities aren&apos;t
              stakeholders to be consulted—they&apos;re leaders to be supported.
              By building on existing traditional governance systems and
              ensuring genuine decision-making power, we create MPAs that
              communities actively protect because they own them.
            </p>

            <h2 className="text-3xl font-semibold text-[var(--color-charcoal)] mt-12 mb-8">
              Core Principles
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 my-8">
              {principles.map((principle, index) => {
                const Icon = principle.icon;
                return (
                  <div
                    key={index}
                    className="bg-[var(--color-cream)] p-8 rounded-lg"
                  >
                    <div className="w-12 h-12 bg-[var(--color-burnt-orange)] rounded-full flex items-center justify-center mb-4">
                      <Icon className="w-6 h-6 text-white" />
                    </div>
                    <h3 className="text-lg font-semibold text-[var(--color-charcoal)] mb-3">
                      {principle.title}
                    </h3>
                    <p className="text-base text-[var(--color-gray)] m-0">
                      {principle.description}
                    </p>
                  </div>
                );
              })}
            </div>

            <h2 className="text-3xl font-semibold text-[var(--color-charcoal)] mt-12 mb-8">
              Our Methodology
            </h2>
            <div className="flex flex-col gap-6 my-8">
              {methodology.map((step, index) => (
                <div
                  key={index}
                  className="p-6 bg-[var(--color-cream)] border-l-4 border-[var(--color-burnt-orange)] rounded"
                >
                  <div className="flex flex-wrap items-center gap-4 mb-3">
                    <span className="text-sm font-semibold text-[var(--color-burnt-orange)] uppercase tracking-wide">
                      {step.phase}
                    </span>
                    <span className="text-sm px-3 py-1 bg-[var(--color-forest-green)] text-white rounded-full">
                      {step.status}
                    </span>
                  </div>
                  <h3 className="text-xl font-semibold text-[var(--color-charcoal)] mb-2">
                    {step.title}
                  </h3>
                  <p className="text-[var(--color-gray)] m-0">
                    {step.description}
                  </p>
                </div>
              ))}
            </div>

            <div className="bg-[var(--color-cream)] p-12 rounded-lg text-center mt-12">
              <h3 className="text-2xl font-semibold text-[var(--color-charcoal)] mb-4">
                Learn More About Our Work
              </h3>
              <p className="text-lg text-[var(--color-gray)] mb-6">
                See how we&apos;re putting these principles into practice in
                Misool, Raja Ampat.
              </p>
              <Button variant="cta" size="md" asChild>
                <Link href="/project">View Project Details</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

// src/routes/approach/+page.svelte
<script lang="ts">
	import Button from '$lib/components/ui/Button.svelte';
</script>

<section class="page-hero">
	<div class="page-hero__container">
		<div class="section-label">[ OUR APPROACH ]</div>
		<h1 class="page-hero__title">Community-Led Conservation Grounded in Science</h1>
		<p class="page-hero__subtitle">
			Building marine protection on trust, accountability, and indigenous knowledge
		</p>
	</div>
</section>

<section class="content-section">
	<div class="content-container">
		<div class="intro-section">
			<p class="intro-text">
				West Papua Care's approach places local communities at the heart of marine conservation, guided by scientific evidence and rooted in traditional knowledge. We're building a model where communities don't just participate in conservation—they lead it.
			</p>
		</div>

		<div class="content-grid">
			<div class="content-main">
				<h2>Core Principles</h2>
				<p>
					As an inception-stage project, we're guided by principles rather than rigid processes. This allows us to remain adaptive, learn as we go, and ensure our approach truly serves both the ecosystem and the communities who depend on it.
				</p>

				<div class="principles-section">
					<div class="principles-grid">
					<div class="principle-card">
						<div class="principle-icon">🤝</div>
						<h3>Community Leadership</h3>
						<p>
							Local voices drive all decisions. We follow Free, Prior and Informed Consent (FPIC) protocols, ensuring communities fully understand the project and retain the power to say no. This isn't consultation—it's genuine partnership where communities hold decision-making authority.
						</p>
						<ul class="principle-points">
							<li>Traditional leaders (kepala suku) guide direction and provide cultural authority</li>
							<li>MPA Committee includes diverse representation: women, youth, fishers, and elders</li>
							<li>Village meetings determine resource use boundaries and protection rules</li>
							<li>Community patrols led by local fishers who know these waters intimately</li>
						</ul>
					</div>

					<div class="principle-card">
						<div class="principle-icon">🔬</div>
						<h3>Science-Backed</h3>
						<p>
							Effective conservation requires evidence. We use internationally recognized Reef Check monitoring protocols to track coral health, fish populations, and ecosystem recovery. But science serves the community—not the other way around.
						</p>
						<ul class="principle-points">
							<li>Quarterly monitoring at GPS-marked sites provides consistent data</li>
							<li>Local fishers trained as citizen scientists, building capacity and ownership</li>
							<li>Data guides adaptive management—if something isn't working, we adjust</li>
							<li>Monitoring tracks spillover benefits to adjacent fishing areas</li>
							<li>IUCN Red List species identification ensures protection of threatened populations</li>
						</ul>
					</div>

					<div class="principle-card">
						<div class="principle-icon">⚖️</div>
						<h3>Trust & Accountability</h3>
						<p>
							Conservation succeeds when communities trust the process and see genuine accountability. We're building systems that are transparent, inclusive, and responsive to community needs and concerns.
						</p>
						<ul class="principle-points">
							<li>Regular community meetings where decisions are explained and feedback heard</li>
							<li>Transparent reporting on finances, monitoring results, and challenges faced</li>
							<li>MPA Committee accountable to communities, not external funders</li>
							<li>Conflict resolution starts with traditional mediation before formal processes</li>
							<li>Success measured by community wellbeing alongside ecological metrics</li>
						</ul>
					</div>

					<div class="principle-card">
						<div class="principle-icon">🌱</div>
						<h3>Indigenous in Decision-Making</h3>
						<p>
							Raja Ampat communities have managed these waters for centuries through traditional systems called <em>sasi</em> and <em>adat</em>. We don't replace these systems—we strengthen them and integrate them with modern conservation tools.
						</p>
						<ul class="principle-points">
							<li>Traditional governance structures provide cultural legitimacy</li>
							<li>Customary law incorporated into protection rules and enforcement</li>
							<li>Elders guide seasonal closures and identify sacred sites</li>
							<li>Indigenous knowledge about fish behavior and reef health informs monitoring</li>
							<li>Decision-making follows traditional consensus-building (musyawarah)</li>
						</ul>
					</div>
					</div>
				</div>

				<h2>Community Benefits</h2>
				<p>
					Marine protection isn't just about conservation—it's about improving community livelihoods and wellbeing. When communities benefit, conservation lasts.
				</p>

				<div class="benefits-section">
					<div class="benefit-item">
						<h4>🐟 Spillover Effect</h4>
						<p>Fish populations in the no-take zone spill into surrounding fishing areas, increasing catches by up to 50%. Healthier reefs mean better fishing for everyone.</p>
					</div>
					<div class="benefit-item">
						<h4>🤿 Ecotourism Revenue</h4>
						<p>Pristine reefs attract divers and tourists, creating sustainable income opportunities for guides, homestays, and local businesses.</p>
					</div>
					<div class="benefit-item">
						<h4>🎓 Education & Training</h4>
						<p>Since March 2024, we've supported English classes, TOEFL preparation, paid internships in Bali, and student exchanges to enhance job readiness.</p>
					</div>
					<div class="benefit-item">
						<h4>💼 Employment Priority</h4>
						<p>Local community members fill all suitable positions, with minimum 30% representation of women, youth, or individuals with disabilities.</p>
					</div>
					<div class="benefit-item">
						<h4>🍽️ Food Security</h4>
						<p>Healthy reefs ensure long-term protein supply for future generations. Conservation is about sustaining the resources families depend on.</p>
					</div>
					<div class="benefit-item">
						<h4>🏆 Cultural Pride</h4>
						<p>Communities recognized as global leaders in marine stewardship, preserving their heritage while protecting their future.</p>
					</div>
				</div>

				<h2>Adaptive & Evaluative</h2>
				<p>
					As an early-stage project, we embrace learning and adaptation. We're guided by principles and evidence, not rigid procedures. This evaluative approach means we:
				</p>
				<ul class="styled-list">
					<li>Regularly assess what's working and what isn't through community feedback and monitoring data</li>
					<li>Adjust strategies based on evidence and community needs</li>
					<li>Document lessons learned—both successes and failures—to improve and share</li>
					<li>Prioritize relationship-building over bureaucratic processes</li>
					<li>Remain flexible enough to respond to emerging challenges and opportunities</li>
					<li>Evaluate progress every 5 years with traditional authorities and community representatives</li>
				</ul>

				<h2>Building for the Long Term</h2>
				<p>
					Our goal isn't to create dependency but to build local capacity for communities to manage the MPA themselves. We invest in training, support sustainable financing through ecotourism and conservation fees, and strengthen traditional governance structures.
				</p>
				<p>
					This isn't charity—it's building the institutional and financial foundation for conservation that lasts 30+ years.
				</p>

				<h2>Base Camp Operations</h2>
				<p>
					Rangers operate from Cempedak Island, equipped with a 100 HP speedboat, surveillance drones, mobile Starlink internet, and accommodation facilities. Community members with traditional land rights retain access while respecting conservation protocols.
				</p>

				<div class="approach-commitment">
					<h3>Our Commitment</h3>
					<p>
						We commit to conservation that respects community autonomy, adapts based on evidence, operates with transparency, and measures success by both ecological recovery and community prosperity. When ecosystems and people both thrive, conservation becomes self-sustaining.
					</p>
				</div>

				<div class="cta-box">
					<h3>Support Community-Led Conservation</h3>
					<p>Join us in building a model where communities and ecosystems thrive together.</p>
					<Button variant="cta" size="md" href="/get-involved">Get Involved</Button>
				</div>
			</div>
		</div>
	</div>
</section>

<style>
	.page-hero {
		background: var(--color-forest-green-deep);
		padding: clamp(8rem, 15vh, 12rem) 0 clamp(3rem, 6vh, 5rem);
		position: relative;
	}

	.page-hero::before {
		content: '';
		position: absolute;
		inset: 0;
		opacity: 0.03;
		background-image: radial-gradient(circle at 1px 1px, rgba(255, 255, 255, 0.15) 1px, transparent 1px);
		background-size: 40px 40px;
	}

	.page-hero__container {
		max-width: var(--max-width-content);
		margin: 0 auto;
		padding: 0 var(--spacing-xl);
		position: relative;
		z-index: 1;
		text-align: center;
	}

	.page-hero__title {
		font-size: clamp(2.5rem, 5vw, 4rem);
		font-weight: 700;
		line-height: 1.2;
		color: var(--color-off-white);
		margin-bottom: var(--spacing-lg);
	}

	.page-hero__subtitle {
		font-size: clamp(1.125rem, 2vw, 1.5rem);
		line-height: 1.6;
		color: rgba(255, 255, 255, 0.9);
		max-width: 800px;
		margin: 0 auto;
	}

	.content-section {
		padding: clamp(4rem, 8vh, 6rem) 0;
		background: var(--color-off-white);
	}

	.content-container {
		max-width: var(--max-width-content);
		margin: 0 auto;
		padding: 0 var(--spacing-xl);
	}

	.intro-section {
		max-width: 900px;
		margin: 0 auto var(--spacing-3xl);
		text-align: center;
	}

	.intro-text {
		font-size: var(--font-size-lg);
		line-height: 1.7;
		color: var(--color-gray);
	}

	.content-grid {
		display: grid;
		grid-template-columns: 1fr;
		gap: var(--spacing-3xl);
	}

	.content-main {
		max-width: 1200px;
		margin: 0 auto;
	}

	.content-main h2 {
		font-size: var(--font-size-2xl);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-top: var(--spacing-3xl);
		margin-bottom: var(--spacing-lg);
	}

	.content-main h2:first-child {
		margin-top: 0;
	}

	.content-main h3 {
		font-size: var(--font-size-xl);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-top: 0;
		margin-bottom: var(--spacing-md);
	}

	.content-main h4 {
		font-size: var(--font-size-lg);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-sm);
	}

	.content-main p {
		font-size: var(--font-size-base);
		line-height: 1.7;
		color: var(--color-gray);
		margin-bottom: var(--spacing-lg);
	}

	.principles-section {
		background: transparent;
		padding: 0;
		border-radius: 0;
		margin: var(--spacing-2xl) 0 var(--spacing-3xl);
	}

	.principles-grid {
		display: grid;
		grid-template-columns: 1fr;
		gap: var(--spacing-3xl);
	}

	.principle-card {
		background: var(--color-cream);
		padding: var(--spacing-3xl);
		border-radius: 12px;
		border: 1px solid rgba(211, 100, 15, 0.15);
	}

	.principle-icon {
		width: 64px;
		height: 64px;
		background: var(--color-burnt-orange);
		border-radius: 12px;
		display: flex;
		align-items: center;
		justify-content: center;
		font-size: 2rem;
		margin-bottom: var(--spacing-lg);
	}

	.principle-card h3 {
		color: var(--color-charcoal);
		font-size: var(--font-size-xl);
		font-weight: 700;
		margin-bottom: var(--spacing-lg);
	}

	.principle-card p {
		color: var(--color-gray);
		font-size: var(--font-size-sm);
		line-height: 1.6;
		margin-bottom: var(--spacing-lg);
	}

	.principle-points {
		list-style: none;
		padding: 0;
		margin: 0;
	}

	.principle-points li {
		padding: var(--spacing-sm) 0;
		padding-left: var(--spacing-lg);
		font-size: var(--font-size-sm);
		color: var(--color-gray);
		position: relative;
		line-height: 1.7;
	}

	.principle-points li::before {
		content: '•';
		position: absolute;
		left: 0;
		color: var(--color-burnt-orange);
		font-size: 1.5em;
		line-height: 1;
	}

	.benefits-section {
		display: grid;
		grid-template-columns: 1fr;
		gap: var(--spacing-lg);
		margin: var(--spacing-xl) 0;
	}

	.benefit-item {
		background: var(--color-cream);
		padding: var(--spacing-lg);
		border-radius: 8px;
	}

	.benefit-item h4 {
		margin-bottom: var(--spacing-sm);
		color: var(--color-charcoal);
	}

	.benefit-item p {
		margin: 0;
		font-size: var(--font-size-sm);
		line-height: 1.6;
		color: var(--color-gray);
	}

	.styled-list {
		list-style: none;
		padding: 0;
		margin: var(--spacing-lg) 0;
	}

	.styled-list li {
		padding-left: var(--spacing-xl);
		margin-bottom: var(--spacing-md);
		position: relative;
		font-size: var(--font-size-base);
		line-height: 1.6;
		color: var(--color-gray);
	}

	.styled-list li::before {
		content: '✓';
		position: absolute;
		left: 0;
		color: var(--color-burnt-orange);
		font-size: 1.2em;
		font-weight: 700;
	}

	.approach-commitment {
		background: linear-gradient(135deg, rgba(211, 100, 15, 0.08) 0%, rgba(211, 100, 15, 0.12) 100%);
		border: 2px solid var(--color-burnt-orange);
		padding: var(--spacing-2xl);
		border-radius: 8px;
		margin: var(--spacing-3xl) 0;
	}

	.approach-commitment h3 {
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-md);
	}

	.approach-commitment p {
		margin: 0;
		font-size: var(--font-size-base);
		line-height: 1.7;
		color: var(--color-gray);
	}

	.cta-box {
		background: var(--color-cream);
		padding: var(--spacing-2xl);
		border-radius: 8px;
		text-align: center;
		margin-top: var(--spacing-3xl);
	}

	.cta-box h3 {
		font-size: var(--font-size-xl);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-md);
	}

	.cta-box p {
		margin-bottom: var(--spacing-lg);
	}

	.content-sidebar {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-xl);
	}

	.info-card {
		background: var(--color-cream);
		padding: var(--spacing-xl);
		border-radius: 8px;
	}

	.info-card h3 {
		font-size: var(--font-size-lg);
		font-weight: 600;
		color: var(--color-charcoal);
		margin-bottom: var(--spacing-lg);
	}

	.values-list,
	.monitoring-list {
		list-style: none;
		padding: 0;
		margin: 0;
	}

	.values-list li,
	.monitoring-list li {
		padding: var(--spacing-xs) 0;
		padding-left: var(--spacing-lg);
		font-size: var(--font-size-sm);
		color: var(--color-gray);
		position: relative;
		line-height: 1.5;
	}

	.values-list li::before,
	.monitoring-list li::before {
		content: '•';
		position: absolute;
		left: 0;
		color: var(--color-burnt-orange);
		font-size: 1.2em;
	}

	.link-list {
		list-style: none;
		padding: 0;
		margin: 0;
		display: flex;
		flex-direction: column;
		gap: var(--spacing-sm);
	}

	.link-list a {
		display: block;
		padding: var(--spacing-sm) var(--spacing-md);
		color: var(--color-charcoal);
		text-decoration: none;
		border-radius: 4px;
		transition: all 0.2s ease;
		font-size: var(--font-size-base);
	}

	.link-list a:hover {
		background: var(--color-off-white);
		color: var(--color-burnt-orange);
	}

	@media (min-width: 768px) {
		.principles-grid {
			grid-template-columns: repeat(2, 1fr);
		}

		.benefits-section {
			grid-template-columns: repeat(2, 1fr);
		}
	}

	@media (min-width: 1024px) {
		.content-grid {
			grid-template-columns: 1fr;
		}

		.principles-grid {
			grid-template-columns: repeat(2, 1fr);
		}

		.benefits-section {
			grid-template-columns: repeat(3, 1fr);
		}
	}
</style>
