// src/lib/components/ui/Button.svelte
<script lang="ts">
	interface Props {
		variant?: 'primary' | 'secondary' | 'cta' | 'link';
		size?: 'sm' | 'md' | 'lg';
		href?: string;
		type?: 'button' | 'submit' | 'reset';
		disabled?: boolean;
		children?: any;
		onclick?: (e: MouseEvent) => void;
	}

	let {
		variant = 'primary',
		size = 'md',
		href,
		type = 'button',
		disabled = false,
		children,
		onclick
	}: Props = $props();

	let className = $derived(`btn btn--${variant} btn--${size}`);
</script>

{#if href}
	<a {href} class={className} role="button" tabindex={disabled ? -1 : 0}>
		{@render children?.()}
	</a>
{:else}
	<button class={className} {type} {disabled} {onclick}>
		{@render children?.()}
	</button>
{/if}

<style>
	.btn {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		font-family: var(--font-family-heading);
		font-weight: 600;
		text-align: center;
		text-decoration: none;
		border: none;
		border-radius: var(--radius);
		cursor: pointer;
		transition: all var(--transition-fast);
		white-space: nowrap;
	}

	.btn:focus-visible {
		outline: 2px solid var(--color-coral-blue);
		outline-offset: 2px;
	}

	/* Sizes */
	.btn--sm {
		padding: var(--spacing-sm) var(--spacing-md);
		font-size: var(--font-size-sm);
	}

	.btn--md {
		padding: var(--spacing-md) calc(var(--spacing-xl) + var(--spacing-sm));
		font-size: var(--font-size-base);
	}

	.btn--lg {
		padding: calc(var(--spacing-md) + var(--spacing-xs)) calc(var(--spacing-2xl) + var(--spacing-sm));
		font-size: var(--font-size-lg);
	}

	/* Variants */
	.btn--primary {
		background: var(--color-primary);
		color: var(--color-off-white);
	}

	.btn--primary:hover:not(:disabled) {
		background: #3d4429;
	}

	.btn--secondary {
		background: transparent;
		color: var(--color-off-white);
		border: 1px solid var(--color-off-white);
	}

	.btn--secondary:hover:not(:disabled) {
		background: rgba(255, 255, 255, 0.1);
		border-color: var(--color-off-white);
	}

	.btn--cta {
		background: var(--color-burnt-orange);
		color: var(--color-off-white);
	}

	.btn--cta:hover:not(:disabled) {
		background: #b8580c;
	}

	.btn--link {
		background: transparent;
		color: var(--color-link);
		padding: 0;
	}

	.btn--link:hover:not(:disabled) {
		color: var(--color-link-hover);
		text-decoration: underline;
	}

	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn:active:not(:disabled) {
		transform: translateY(0);
	}
</style>

// src/components/ui/button.tsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-base font-semibold font-[var(--font-family-heading)] transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-burnt-orange)] focus-visible:ring-offset-2",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive text-white hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
        outline:
          "border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50",
        secondary:
          "bg-[var(--color-forest-green)] !text-white hover:!text-white hover:bg-[var(--color-forest-green-dark)]",
        ghost:
          "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
        link: "!text-[var(--color-burnt-orange)] underline-offset-4 hover:underline p-0 h-auto font-semibold",
        // Custom variants for West Papua Care
        primary:
          "bg-[var(--color-forest-green)] !text-white hover:!text-white hover:bg-[var(--color-forest-green-dark)]",
        cta: "bg-[var(--color-burnt-orange)] !text-white hover:!text-white hover:bg-[var(--color-burnt-orange-dark)] shadow-md hover:shadow-lg",
      },
      size: {
        default: "h-11 px-6 py-2",
        sm: "h-9 rounded-md gap-1.5 px-4 text-sm",
        md: "h-12 px-8 py-3",
        lg: "h-14 rounded-md px-10 text-lg",
        icon: "size-9",
        "icon-sm": "size-8",
        "icon-lg": "size-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot : "button"

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
